client = [
    "us-west2-docker.pkg.dev/divviup-artifacts-public/janus/janus_interop_client:0.6.0-prerelease-2",
]
leader = [
    "us-west2-docker.pkg.dev/divviup-artifacts-public/janus/janus_interop_aggregator:0.6.0-prerelease-2",
]
helper = [
    "us-west2-docker.pkg.dev/divviup-artifacts-public/janus/janus_interop_aggregator:0.6.0-prerelease-2",
]
collector = [
    "us-west2-docker.pkg.dev/divviup-artifacts-public/janus/janus_interop_collector:0.6.0-prerelease-2",
]
